virtualenv .venv --python=python3.11
source .venv/bin/activate
pip install -r requirements.txt


npm install

# Creating super user
#echo "Adding local superuser (admin)"
echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin2').exists() or User.objects.create_superuser('admin2', 'admin@dcs.com', 'adminpass')" | python manage.py shell

make load-data
make start

